# Generated by Django 5.1.15 on 2026-07-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_drop_variant_photo'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('name_fa',), name='uniq_product_name_fa'),
        ),
    ]
