# Generated by Django 5.1.15 on 2026-07-17 11:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def create_opening_batches(apps, schema_editor):
    """Give every already-stocked variant one opening lot at its current price/quantity.

    Keeps day-one valuation and FIFO identical to before batches existed. No StockMovement is
    written — this is an opening balance, not a new receipt.
    """
    ProductVariant = apps.get_model("inventory", "ProductVariant")
    StockBatch = apps.get_model("inventory", "StockBatch")
    for variant in ProductVariant.objects.filter(quantity__gt=0).iterator():
        StockBatch.objects.create(
            variant=variant,
            purchase_price=variant.purchase_price,
            sale_price=variant.sale_price,
            quantity_initial=variant.quantity,
            quantity_remaining=variant.quantity,
            received_at=variant.created_at,
            note="opening balance",
        )


def drop_opening_batches(apps, schema_editor):
    StockBatch = apps.get_model("inventory", "StockBatch")
    StockBatch.objects.filter(note="opening balance").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_uniq_product_name_fa'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_price', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('sale_price', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('quantity_initial', models.PositiveIntegerField()),
                ('quantity_remaining', models.PositiveIntegerField()),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.productvariant')),
            ],
            options={
                'ordering': ['received_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StockAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_purchase_price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('unit_sale_price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='inventory.stockmovement')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='inventory.stockbatch')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.RunPython(create_opening_batches, drop_opening_batches),
    ]
